[package]
name = "pureth-withdrawal-root"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
alloy-eips.workspace = true
alloy-primitives.workspace = true
tree_hash.workspace = true
