consensus:
  enabled: true
  url: "http://host.docker.internal:33500"
  name: "op-node-rpc2"
execution:
  enabled: true
  url: "http://host.docker.internal:29545"
  name: "op-reth-rpc2"
  modules:
    - "eth"
    - "net"
    - "web3"