[package]
name = "reth-pureth-block"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Composed execution block commitments"

[lints]
workspace = true

[dependencies]
alloy-primitives.workspace = true
reth-pureth-ssz.workspace = true
