[package]
name = "reth-snap-sync"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "snap/2 state synchronization"

[lints]
workspace = true

[dependencies]
# reth
reth-primitives-traits.workspace = true
reth-storage-api.workspace = true
reth-storage-errors.workspace = true

# alloy
alloy-eip7928.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true

# misc
thiserror.workspace = true
tokio-util.workspace = true

[dev-dependencies]
alloy-consensus.workspace = true
reth-provider = { workspace = true, features = ["test-utils"] }
