[package]
name = "reth-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
revm.workspace = true
# reth
reth-revm.workspace = true
reth-execution-errors.workspace = true
reth-execution-types.workspace = true
reth-metrics = { workspace = true, optional = true }
reth-primitives-traits.workspace = true
reth-storage-api.workspace = true
reth-storage-errors = { workspace = true, optional = true }
reth-trie-common.workspace = true

evm2.workspace = true

# alloy
alloy-evm.workspace = true
alloy-primitives.workspace = true
alloy-eips.workspace = true
alloy-consensus.workspace = true
alloy-eip7928.workspace = true
alloy-rlp = { workspace = true, optional = true }
alloy-rpc-types-debug = { workspace = true, optional = true }

auto_impl.workspace = true
futures-util.workspace = true
metrics = { workspace = true, optional = true }
moka = { workspace = true, features = ["sync"], optional = true }
rayon = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
fixed-cache.workspace = true

[dev-dependencies]
reth-ethereum-primitives.workspace = true

[features]
default = ["std"]
gmp = ["evm2/gmp"]
asm-keccak = [
    "evm2/asm-keccak",
    "reth-execution-types/asm-keccak",
    "reth-storage-api/asm-keccak",
    "alloy-primitives/asm-keccak",
    "revm/asm-keccak",
    "alloy-evm/asm-keccak",
]
c-kzg = [
    "evm2/c-kzg",
    "reth-execution-types/c-kzg",
]
blst = [
    "evm2/blst",
    "reth-execution-types/blst",
]
portable = [
    "evm2/portable",
    "reth-execution-types/portable",
    "revm/portable",
    "reth-revm/portable",
]
p256-aws-lc-rs = [
    "evm2/p256-aws-lc-rs",
    "reth-execution-types/p256-aws-lc-rs",
]
std = [
    "alloy-evm/std",
    "reth-revm/std",
    "dep:moka",
    "dep:rayon",
    "dep:tracing",
    "reth-primitives-traits/dashmap",
    "reth-primitives-traits/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "alloy-consensus/std",
    "evm2/std",
    "evm2/secp256k1",
    "reth-execution-errors/std",
    "reth-execution-types/std",
    "reth-storage-errors/std",
    "reth-trie-common/std",
    "futures-util/std",
    "reth-storage-api/std",
    "reth-ethereum-primitives/std",
    "tracing?/std",
    "alloy-eip7928/std",
    "fixed-cache/std",
    "alloy-rlp?/std",
    "revm/std",
]
metrics = ["std", "dep:metrics", "dep:reth-metrics"]
witness = ["dep:alloy-rlp", "dep:alloy-rpc-types-debug", "dep:reth-storage-errors"]
test-utils = [
    "reth-primitives-traits/test-utils",
    "reth-trie-common/test-utils",
    "reth-ethereum-primitives/test-utils",
    "reth-revm/test-utils",
]
