[package]
name = "reth-pureth-query"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
alloy-primitives = { workspace = true, features = ["serde"] }
reth-pureth-receipt.workspace = true
serde = { workspace = true, features = ["derive"] }
sha2.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
jsonrpsee = { workspace = true, features = ["server", "macros"] }

[dev-dependencies]
alloy-consensus.workspace = true
reth-ethereum-primitives.workspace = true
reth-primitives-traits.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
