[fixture]
repository = "ethereum/execution-apis"
revision = "main"
track_latest = true
github_token_env = "GITHUB_TOKEN"
cache_dir = "../../../.cache/rpc-compat"
tests_dir = "tests"

[run]
include = ["*"]
exclude = []
skip = []
ignore = []
expected_failures = [
    "debug_getRawTransaction/get-invalid-hash",
    "debug_getRawReceipts/get-block-n",
    "eth_getBlockReceipts/get-block-receipts-by-hash",
    "eth_getBlockReceipts/get-block-receipts-n",
    "eth_getStorageAt/get-storage-invalid-key-too-large",
    "eth_getTransactionReceipt/get-legacy-contract",
    "eth_getTransactionReceipt/get-legacy-input",
    "eth_getTransactionReceipt/get-legacy-receipt",
    "eth_simulateV1/ethSimulate-basefee-too-low-with-validation-38012",
    "eth_simulateV1/ethSimulate-blobs",
    "eth_simulateV1/ethSimulate-check-invalid-nonce",
    "eth_simulateV1/ethSimulate-check-that-nonce-increases",
    "eth_simulateV1/ethSimulate-eth-send-should-not-produce-logs-on-revert",
    "eth_simulateV1/ethSimulate-eth-send-should-produce-logs",
    "eth_simulateV1/ethSimulate-eth-send-should-produce-more-logs-on-forward",
    "eth_simulateV1/ethSimulate-eth-send-should-produce-no-logs-on-forward-revert",
    "eth_simulateV1/ethSimulate-fee-recipient-receiving-funds",
    "eth_simulateV1/ethSimulate-gas-fees-and-value-error-38014-with-validation",
    "eth_simulateV1/ethSimulate-overflow-nonce-validation",
    "eth_simulateV1/ethSimulate-overflow-nonce",
    "eth_simulateV1/ethSimulate-override-address-twice-in-separate-BlockStateCalls",
    "eth_simulateV1/ethSimulate-override-ecrecover",
    "eth_simulateV1/ethSimulate-self-destructive-contract-produces-logs",
    "eth_simulateV1/ethSimulate-send-eth-and-delegate-call-to-eoa",
    "eth_simulateV1/ethSimulate-send-eth-and-delegate-call-to-payble-contract",
    "eth_simulateV1/ethSimulate-send-eth-and-delegate-call",
    "eth_simulateV1/ethSimulate-simple-no-funds-with-validation-without-nonces",
    "eth_simulateV1/ethSimulate-simple-no-funds-with-validation",
    "eth_simulateV1/ethSimulate-simple-send-from-contract-with-validation",
    "eth_simulateV1/ethSimulate-simple-send-from-contract",
    "eth_simulateV1/ethSimulate-simple-validation-fulltx",
    "eth_simulateV1/ethSimulate-use-as-many-features-as-possible",
]
expected_failures_when_error_data_checked = [
    "debug_getRawBlock/get-invalid-number",
    "debug_getRawHeader/get-invalid-number",
    "debug_getRawReceipts/get-invalid-number",
    "eth_getStorageAt/get-storage-invalid-key",
]
timeout_secs = 5
fail_fast = false
ignore_error_data = true
report_json = "../../../target/rpc-compat/report.json"
report_junit = "../../../target/rpc-compat/junit.xml"
