[package]
name = "example-node-custom-rpc"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
reth-ethereum = { workspace = true, features = ["node", "pool", "cli"] }

clap = { workspace = true, features = ["derive"] }
reth-json-rpc = { workspace = true, features = ["macros"] }
tokio.workspace = true
serde_json.workspace = true

[dev-dependencies]
reth-json-rpc = { workspace = true, features = ["http-client", "server", "ws-client"] }

[lints]
