[package]
name = "reth-pureth-ssz"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Retained SSZ trees for execution objects"

[lints]
workspace = true

[dependencies]
alloy-primitives.workspace = true
tree_hash.workspace = true
