[package]
name = "reth-rayon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Rayon operations routed for deterministic execution"

[lints]
workspace = true

[dependencies]
rayon.workspace = true
