# Runs `cargo update` periodically.

name: Update Dependencies

on:
  schedule:
    # Run weekly
    - cron: "0 0 * * SUN"
  workflow_dispatch:
    # Needed so we can run it manually

permissions: {}

jobs:
  update:
    if: github.repository == 'paradigmxyz/reth'
    permissions:
      contents: read
      id-token: write
    uses: tempoxyz/gh-actions/.github/workflows/cargo-update-pr.yml@117919c943b804057be733b0c4034c5542e58959 # 2026-09-23T05-09-41Z-117919c9
