# Runs `cargo update` periodically.

name: Update Dependencies

on:
  schedule:
    # Run weekly
    - cron: "0 0 * * SUN"
  workflow_dispatch:
    # Needed so we can run it manually

permissions: {}

jobs:
  update:
    if: github.repository == 'paradigmxyz/reth'
    permissions:
      contents: read
      id-token: write
    uses: tempoxyz/gh-actions/.github/workflows/cargo-update-pr.yml@ee2960a6cc25d99bda45614135bfe1197d879bac # 2026-09-26T06-46-03Z-ee2960a6
