# Runs `cargo update` periodically.

name: Update Dependencies

on:
  schedule:
    # Run weekly
    - cron: "0 0 * * SUN"
  workflow_dispatch:
    # Needed so we can run it manually

permissions: {}

jobs:
  update:
    if: github.repository == 'paradigmxyz/reth'
    permissions:
      contents: read
      id-token: write
    uses: tempoxyz/ci/.github/workflows/cargo-update-pr.yml@921d47ce30160fb82a5181c840b41fbbac77c18f
