# Runs e2e tests using the testsuite framework

name: e2e

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  SEED: rustethereumethereumrust
  RUSTC_WRAPPER: "sccache"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: e2e-testsuite
    runs-on: ${{ github.repository == 'paradigmxyz/reth' && 'depot-ubuntu-latest-4' || 'ubuntu-latest' }}
    permissions:
      contents: read
    env:
      RUST_BACKTRACE: 1
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: rui314/setup-mold@7e4f20ad28a2e8ca6fd0892ccf72e2abb706b9c3 # v1
      - run: .github/scripts/install_llvm.sh ubuntu
      - uses: dtolnay/rust-toolchain@stable
      - uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # v0.0.11
      - uses: taiki-e/install-action@b6b84cf49ebfe0176417bdce007c624f0db37f20 # v2.86.2
        with:
          tool: nextest
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          cache-targets: false
          cache-on-failure: true
      - name: Run e2e tests
        run: |
          cargo nextest run \
            --no-fail-fast \
            --locked --features "asm-keccak" \
            --workspace \
            --exclude 'example-*' \
            --exclude 'exex-subscription' \
            --exclude 'ef-tests' \
            --exclude 'reth' \
            -E 'binary(e2e_testsuite)'

  rocksdb:
    name: e2e-rocksdb
    runs-on: ${{ github.repository == 'paradigmxyz/reth' && 'depot-ubuntu-latest-4' || 'ubuntu-latest' }}
    permissions:
      contents: read
    env:
      RUST_BACKTRACE: 1
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: rui314/setup-mold@7e4f20ad28a2e8ca6fd0892ccf72e2abb706b9c3 # v1
      - run: .github/scripts/install_llvm.sh ubuntu
      - uses: dtolnay/rust-toolchain@stable
      - uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # v0.0.11
      - uses: taiki-e/install-action@b6b84cf49ebfe0176417bdce007c624f0db37f20 # v2.86.2
        with:
          tool: nextest
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          cache-on-failure: true
      - name: Run RocksDB e2e tests
        run: |
          cargo nextest run \
            --no-fail-fast \
            --locked \
            -p reth-e2e-test-utils \
            -E 'binary(rocksdb)'
      - name: Free disk before post steps
        if: always()
        run: |
          sccache --stop-server || true
          rm -rf target ~/.cache/sccache
          df -h
