# Runs e2e tests using the testsuite framework

name: e2e

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  SEED: rustethereumethereumrust
  RUSTC_WRAPPER: "sccache"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: e2e-testsuite
    runs-on: ${{ github.repository == 'paradigmxyz/reth' && 'depot-ubuntu-latest-8' || 'ubuntu-latest' }}
    permissions:
      contents: read
    env:
      RUST_BACKTRACE: 1
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444 # v1
      - run: .github/scripts/install_llvm.sh ubuntu
      - uses: dtolnay/rust-toolchain@stable
      - uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10
      - uses: taiki-e/install-action@43aecc8d72668fbcfe75c31400bc4f890f1c5853 # v2.83.2
        with:
          tool: nextest
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          cache-on-failure: true
      - name: Run e2e tests
        run: |
          cargo nextest run \
            --no-fail-fast \
            --locked --features "asm-keccak" \
            --workspace \
            --exclude 'example-*' \
            --exclude 'exex-subscription' \
            --exclude 'ef-tests' \
            --exclude 'reth' \
            -E 'binary(e2e_testsuite)'

  rocksdb:
    name: e2e-rocksdb
    runs-on: ${{ github.repository == 'paradigmxyz/reth' && 'depot-ubuntu-latest-4' || 'ubuntu-latest' }}
    permissions:
      contents: read
    env:
      RUST_BACKTRACE: 1
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444 # v1
      - run: .github/scripts/install_llvm.sh ubuntu
      - uses: dtolnay/rust-toolchain@stable
      - uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10
      - uses: taiki-e/install-action@43aecc8d72668fbcfe75c31400bc4f890f1c5853 # v2.83.2
        with:
          tool: nextest
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          cache-on-failure: true
      - name: Run RocksDB e2e tests
        run: |
          cargo nextest run \
            --no-fail-fast \
            --locked \
            -p reth-e2e-test-utils \
            -E 'binary(rocksdb)'
      - name: Free disk before post steps
        if: always()
        run: |
          sccache --stop-server || true
          rm -rf target ~/.cache/sccache
          df -h
