# Runs `assertoor` tests on a `kurtosis` testnet.

name: kurtosis

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  build-reth:
    if: github.repository == 'paradigmxyz/reth'
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/docker-test.yml
    with:
      hive_target: kurtosis
    secrets: inherit

  test:
    timeout-minutes: 60
    strategy:
      fail-fast: false
    name: run kurtosis
    runs-on: ${{ github.repository == 'paradigmxyz/reth' && 'depot-ubuntu-latest' || 'ubuntu-latest' }}
    permissions:
      contents: read
    needs:
      - build-reth
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Download reth image
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: artifacts
          path: /tmp

      - name: Load Docker image
        run: |
          docker load -i /tmp/reth_image.tar &
          wait
          docker image ls -a

      - name: Run kurtosis
        uses: ethpandaops/kurtosis-assertoor-github-action@f64942cbc780df731a731ea9f45765b161d2c8df # v1.0.1
        with:
          ethereum_package_args: ".github/assets/kurtosis_network_params.yaml"

  notify-on-error:
    needs: test
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Slack Webhook Action
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: "Failed run: https://github.com/paradigmxyz/reth/actions/runs/${{ github.run_id }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_HIVE_WEBHOOK_URL }}
