name: Lint GitHub Actions workflows
on:
  pull_request:
    paths:
    - '.github/**'
  merge_group:
  push:
    paths:
    - '.github/**'

permissions: {}

jobs:
  actionlint:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Secure runner
        uses: tempoxyz/gh-actions/actions/secure-runner@48ff2b0c97ede86c9f10d105424380b9605f790d
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.25'
          cache: false
      - name: Install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@v1.7.12
      - name: Check workflow files
        run: SHELLCHECK_OPTS="-S error" actionlint -color
        shell: bash
