# This workflow auto-publishes Reth to external package managers such as
# Homebrew when a release is published.

name: release externally

on:
  release:
    types: [published]

permissions: {}

jobs:
  release-homebrew:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Secure runner
        uses: tempoxyz/gh-actions/actions/secure-runner@7e2ea6e1a8f5a22f16c2d4b389ffde25da93fa1b # 2026-09-22T22-21-59Z-7e2ea6e1
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@b12d2bc99c46444125e606142f28200ec71a1214 # v10
        with:
          token: ${{ secrets.HOMEBREW }}
          no_fork: true
          tap: paradigmxyz/brew
          formula: reth
