# This workflow auto-publishes Reth to external package managers such as
# Homebrew when a release is published.

name: release externally

on:
  release:
    types: [published]

permissions: {}

jobs:
  release-homebrew:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@a0e064e08103c01870c6d1b05168d1b726aab119 # v8
        with:
          token: ${{ secrets.HOMEBREW }}
          no_fork: true
          tap: paradigmxyz/brew
          formula: reth
