# This workflow auto-publishes Reth to external package managers such as
# Homebrew when a release is published.

name: release externally

on:
  release:
    types: [published]

permissions: {}

jobs:
  release-homebrew:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@1446dca236b0440c6f02723a3f14f13be2c04ab0 # v7
        with:
          token: ${{ secrets.HOMEBREW }}
          no_fork: true
          tap: paradigmxyz/brew
          formula: reth
